FROM php:7.4-fpm-alpine

RUN apk update && apk upgrade

RUN apk add grpc
RUN apk add protobuf
RUN apk add composer

RUN apk add libstdc++
RUN apk add zlib-dev
RUN apk add git make g++ unzip autoconf automake libtool file openssl curl
RUN apk add linux-headers

RUN pecl install grpc
RUN pecl install protobuf

RUN docker-php-ext-install pdo_mysql
RUN apk add php-pdo php-pdo_mysql php-mysqli php-phar

RUN echo "extension=grpc.so" >> /usr/local/etc/php/conf.d/docker-php-ext-grpc.ini
RUN echo "extension=protobuf.so" >> /usr/local/etc/php/conf.d/docker-php-ext-protobuf.ini
# RUN echo "extension=mysql.so" >> /usr/local/etc/php/conf.d/docker-php-ext-pdo.ini
# RUN echo "extension=pdo.so" >> /usr/local/etc/php/conf.d/docker-php-ext-pdo.ini
# RUN echo "extension=pdo_mysql.so" >> /usr/local/etc/php/conf.d/docker-php-ext-pdo.ini

# RUN apk add libfreetype6-dev libjpeg62-turbo-dev libpng-dev
# RUN docker-php-ext-configure gd --with-freetype --with-jpeg
# RUN docker-php-ext-install -j$(nproc) gd
# RUN apk add libicu-dev 
# RUN docker-php-ext-configure intl 
# RUN docker-php-ext-install intl
RUN pecl channel-update pecl.php.net
RUN pecl install xdebug-2.8.1
RUN docker-php-ext-enable xdebug

RUN echo "xdebug.remote_enable=1\n\
xdebug.remote_autostart=1\n\
xdebug.remote_connect_back=0\n\
xdebug.remote_port=9001\n\
xdebug.remote_host=docker.for.mac.localhost\n\
xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/xdebug.ini \
&& sed -i 's/request_terminate_timeout/;request_terminate_timeout/' /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www/html
EXPOSE 9000

ADD . /var/www/html

RUN "composer" "dump-autoload"

CMD ["php-fpm","--allow-to-run-as-root"]