version: '3'
services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - ahaverse-cms
  #   volumes:
  #     - "/Users/aha_cm/Documents/docker-env/php@7.4:/etc/nginx/conf.d:ro"
  #   container_name: "nginx"
  ahaverse-cms:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    image: ahaverse-cms:0.0.1
    container_name: ahaverse-cms
    ports:
      - "8081:8000"
      - "9000:9000"
    volumes:
      - "/Users/aha_cm/Documents/ahaverse_cms:/var/www/php:ro"